name: CMake Multi-Platform

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            triplet: x86-windows          # 32-bit dla MTA
            generator: "Visual Studio 17 2022"
            arch: Win32
          - os: ubuntu-latest
            triplet: x64-linux
            generator: "Ninja"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommit: 'master'
          vcpkgJsonGlob: 'vcpkg.json'
          vcpkgBinaryCaching: true

      - name: Configure CMake
        run: >
          cmake -B ${{ github.workspace }}/build
          -G "${{ matrix.generator }}"
          -A ${{ matrix.arch }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
          -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} -j 2
